<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-H4443VU" failures="1" tests="4" name="testNGAssertStudy.AssertionStudy" time="0.327" errors="0" timestamp="2022-06-20T13:44:29 GMT-11:00" skipped="0">
  <testcase classname="testNGAssertStudy.AssertionStudy" name="AssertNullStudy" time="0.091"/>
  <system-out>
    <![CDATA[Feld is null TC is Passed]]>
  </system-out>
  <testcase classname="testNGAssertStudy.AssertionStudy" name="AssertEqualsStudy" time="0.094">
    <failure message="Text not matching TC is failed expected [Login to Kit] but found [Login to Kite]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Text not matching TC is failed expected [Login to Kit] but found [Login to Kite]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testNGAssertStudy.AssertionStudy.AssertEqualsStudy(AssertionStudy.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AssertEqualsStudy -->
  <system-out/>
  <testcase classname="testNGAssertStudy.AssertionStudy" name="AssertNotEqualsStudy" time="0.048"/>
  <system-out>
    <![CDATA[Tc is passed]]>
  </system-out>
  <testcase classname="testNGAssertStudy.AssertionStudy" name="Asserttruestudy" time="0.094"/>
  <system-out>
    <![CDATA[Button is displayed Tc is Pass]]>
  </system-out>
</testsuite> <!-- testNGAssertStudy.AssertionStudy -->
